title: My page!
author: Ray-13
email: raymondbayat@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ray's page! Made with github pages.

# social links
github_username:  RayFB-13 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
